#!/bin/sh
PROGRAM_PATH=$(readlink -f $0 | xargs dirname ) 

export XDG_CONFIG_DIRS=${PROGRAM_PATH}
LINES=10
TITLE="ymenu"

while getopts "l:p:v?" option;do
  case "${option}" in
    l)
      LINES="${OPTARG}"
      ;;
    p)
      TITLE="${OPTARG}"
      ;;
    v)
      echo "1.0"
      exit
      ;;
    :)
      echo ":"
      exit
      ;;
    *)
      echo "*"
      exit
      ;;
  esac
done

  # --height 800 --width 800 \
yad --list --title="${TITLE}" --column='' \
  --hide-header \
  --search-column=1 \
  --no-buttons --separator='' \
  --no-headers --close-on-unfocus  \
  --skip-taskbar \
  --sticky \
  --regex-search \
  --no-markup \
  --borders=0 \
  --geometry=1200x580 \
  --css ${PROGRAM_PATH}/ymenu.gtk.css \
  --center \
  --name ymenu

# --no-cancel
